module.exports = Object.freeze({
    // Auth
    AUTH_TWITTER: 'AUTH_TWITTER',
    AUTH_TWITTER_COMPLETE: 'AUTH_TWITTER_COMPLETE',
    AUTH_TWITTER_ERROR: 'AUTH_TWITTER_ERROR',

    AUTH_MIXER: 'AUTH_MIXER',
    AUTH_MIXER_COMPLETE: 'AUTH_MIXER_COMPLETE',
    AUTH_MIXER_ERROR: 'AUTH_MIXER_ERROR',

    // Window Management
    NEW_WINDOW: 'NEW_WINDOW',
    OPEN_MONITOR_WINDOW: 'OPEN_MONITOR_WINDOW',
    TOGGLE_STREAM_WINDOW_FROM_TRAY: 'TOGGLE_STREAM_WINDOW_FROM_TRAY',
    SHOW_APP_WINDOW_FROM_TRAY: 'SHOW_APP_WINDOW_FROM_TRAY',

    // Generic Windows
    WINDOW_FIND_START: 'WINDOW_FIND_START',
    WINDOW_FIND_NEXT: 'WINDOW_FIND_NEXT',
    WINDOW_ZOOM_IN: 'WINDOW_ZOOM_IN',
    WINDOW_ZOOM_OUT: 'WINDOW_ZOOM_OUT',
    WINDOW_ZOOM_RESET: 'WINDOW_ZOOM_RESET',
    WINDOW_RELOAD_WEBVIEW: 'WINDOW_RELOAD_WEBVIEW',
    WINDOW_NAVIGATE_WEBVIEW_BACK: 'WINDOW_NAVIGATE_WEBVIEW_BACK',
    WINDOW_NAVIGATE_WEBVIEW_FORWARD: 'WINDOW_NAVIGATE_WEBVIEW_FORWARD',

    // App Window
    STORAGE_CHANGE_ACTIVE: 'STORAGE_CHANGE_ACTIVE',
    WINDOW_JS_LOADED: 'WINDOW_JS_LOADED',
    STREAMS_WINDOW_PREPARE_RELOAD: 'STREAMS_WINDOW_PREPARE_RELOAD',
    STREAMS_WINDOW_TOGGLE_SIDEBAR: 'STREAMS_WINDOW_TOGGLE_SIDEBAR',
    STREAMS_WINDOW_TOGGLE_APP_MENU: 'STREAMS_WINDOW_TOGGLE_APP_MENU',
    STREAMS_WINDOW_DOWNLOAD_COMPLETE: 'STREAMS_WINDOW_DOWNLOAD_COMPLETE',
    STREAMS_WINDOW_STREAM_WEBVIEW_ATTACHED: 'STREAMS_WINDOW_STREAM_WEBVIEW_ATTACHED',
    WINDOW_LIFECYCLE_HIBERNATE: 'WINDOW_LIFECYCLE_HIBERNATE',
    WINDOW_LIFECYCLE_AWAKEN: "WINDOW_LIFECYCLE_AWAKEN",
    STREAMS_WINDOW_SHOW_SETTINGS: 'WINDOW_SHOW_SETTINGS',
    STREAMS_WINDOW_ADD_ACCOUNT: 'WINDOW_ADD_ACCOUNT',
    STREAMS_WINDOW_FETCH_OPEN_WINDOW_COUNT: 'STREAMS_WINDOW_FETCH_OPEN_WINDOW_COUNT',
    STREAMS_WINDOW_OPEN_MAILTO_LINK: 'STREAMS_WINDOW_OPEN_MAILTO_LINK',
    STREAMS_WINDOW_SWITCH_STREAM: 'STREAMS_WINDOW_SWITCH_STREAM',
    STREAMS_WINDOW_SWITCH_SERVICE_INDEX: 'STREAMS_WINDOW_SWITCH_SERVICE_INDEX',

    // App
    APP_NOTIFICATION_CLICK: 'APP_NOTIFICATION_CLICK',
    APP_NOTIFICATION_PRESENT: 'APP_NOTIFICATION_PRESENT',
    APP_ELEVATED_LOG: 'APP_ELEVATED_LOG',
    APP_ELEVATED_ERROR: 'APP_ELEVATED_ERROR',
    APP_COMPOSE_MESSAGE: 'APP_COMPOSE_MESSAGE',

    // Resource usage
    PING_RESOURCE_USAGE: 'PING_RESOURCE_USAGE',
    PONG_RESOURCE_USAGE: 'PONG_RESOURCE_USAGE',
    SUBMIT_PROCESS_RESOURCE_USAGE: 'SUBMIT_PROCESS_RESOURCE_USAGE',

    // App lifecycle
    FOCUS_APP: 'FOCUS_APP',
    QUIT_APP: 'QUIT_APP',
    RELAUNCH_APP: 'RELAUNCH_APP',

    // Squirrel & Update
    SQUIRREL_UPDATE_CHECK: 'SQUIRREL_UPDATE_CHECK',
    SQUIRREL_APPLY_UPDATE: 'SQUIRREL_APPLY_UPDATE',
    USER_CHECK_FOR_UPDATE: 'USER_CHECK_FOR_UPDATE',
    SQUIRREL_UPDATE_DOWNLOADED: 'SQUIRREL_UPDATE_DOWNLOADED',
    SQUIRREL_UPDATE_ERROR: 'SQUIRREL_UPDATE_ERROR',
    SQUIRREL_UPDATE_AVAILABLE: 'SQUIRREL_UPDATE_AVAILABLE',
    SQUIRREL_UPDATE_NOT_AVAILABLE: 'SQUIRREL_UPDATE_NOT_AVAILABLE',
    SQUIRREL_UPDATE_CHECK_START: 'SQUIRREL_UPDATE_CHECK_START',
    SQUIRREL_UPDATE_DISABLED: 'SQUIRREL_UPDATE_DISABLED',

    // Session management
    PREPARE_SESSION: 'PREPARE_SESSION',

    // Misc
    SEND_IPC_TO_CHILD: 'SEND_IPC_TO_CHILD'
})